config/routes.rb
Rails.application.routes.draw do
  devise_for :couriers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :waybills do 
    member do 
      put :yiqu
    end
  end

  resources :couriers do 
    member do 
      post :login
    end
  end

  root to: 'waybills#index'

  resources :waybills do
    resources :items
  end
end

app/models/waybill.rb
class Waybill < ApplicationRecord
  belongs_to :order

  belongs_to :sender, polymorphic: true
  belongs_to :receiver, polymorphic: true

  has_one :waybill

  def can_qujian?
    self.status == 1
  end

  def yiqu
    if self.status == 1
      self.update_attributes(status: 2, actual_time: Time.now)
      true
    else
      false
    end
  end
end

app/controllers/waybills_controller.rb
class WaybillsController < ApplicationController
  before_action :set_waybill, only: [:show, :edit, :update, :destroy, :yiqu]

  # GET /waybills
  # GET /waybills.json
  def index
    @pickup_waybills = current_courier.pickup_waybills
    @deliver_waybills = current_courier.deliver_waybills
  end

  # GET /waybills/1
  # GET /waybills/1.json
  def show
  end

  # GET /waybills/new
  def new
    @waybill = Waybill.new
  end

  # GET /waybills/1/edit
  def edit
  end

  # POST /waybills
  # POST /waybills.json
  def create
    @waybill = Waybill.new(waybill_params)

    respond_to do |format|
      if @waybill.save
        format.html { redirect_to @waybill, notice: 'Waybill was successfully created.' }
        format.json { render :show, status: :created, location: @waybill }
      else
        format.html { render :new }
        format.json { render json: @waybill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waybills/1
  # PATCH/PUT /waybills/1.json
  def update
    respond_to do |format|
      if @waybill.update(waybill_params)
        format.html { redirect_to @waybill, notice: 'Waybill was successfully updated.' }
        format.json { render :show, status: :ok, location: @waybill }
      else
        format.html { render :edit }
        format.json { render json: @waybill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waybills/1
  # DELETE /waybills/1.json
  def destroy
    @waybill.destroy
    respond_to do |format|
      format.html { redirect_to waybills_url, notice: 'Waybill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def yiqu
    respond_to do |format|
      if @waybill.yiqu
        format.html { redirect_to :back, notice: '取件成功.' }
      else
        format.html { redirect_to :back, alert: "取件失败. #{@waybill.errors}" }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waybill
      @waybill = Waybill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def waybill_params
      params.fetch(:waybill, {})
    end
end

app/helpers/waybills_helper.rb
module WaybillsHelper
  def show_waybill_status(status)
    case status
    when 0
      '初始'
    when 1
      '进行中'
    when 2
      '已完成'
    end
  end
end

app/views/waybills/_form.html.slim
= simple_form_for(@waybill) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/waybills/edit.html.slim
h1 Editing waybill

== render 'form'

= link_to 'Show', @waybill
'|
= link_to 'Back', waybills_path

app/views/waybills/index.html.slim
.row
  .col-md-12
    .panel.panel-default
      .panel-heading#operations
        | 取件单
      .panel-body
        table.table.table-striped
          thead
            tr
              th width='15%' 从
              th width='15%' 到
              th width='15%' 状态
              th width='15%' 期望执行
              th width='15%' 实际执行
              th
          tbody
            - @pickup_waybills.each do |waybill|
              tr
                td
                  - if waybill.sender_type == 'User' 
                    = waybill.order.address
                  - else
                    = waybill.sender.address
                td
                  - if waybill.sender_type == 'User' 
                    = waybill.order.address
                  - else
                    = waybill.sender.address
                td
                  = show_waybill_status waybill.status
                td
                  = date_time waybill.exp_time
                td
                  = date_time waybill.actual_time
                td = link_to 'Show', waybill

.row
  .col-md-12
    .panel.panel-default
      .panel-heading#operations
        | 送件单
      .panel-body
        table.table.table-striped
          thead
            tr
              th width='15%' 联系人
              th width='15%' 地址
              th width='15%' 状态
              th width='15%' 期望执行
              th width='15%' 实际执行
              th
          tbody
            - @deliver_waybills.each do |waybill|
              tr
                td
                  - if waybill.receiver_type == 'User' 
                    = waybill.order.address
                  - else
                    = waybill.receiver.address
                td
                  - if waybill.receiver_type == 'User' 
                    = waybill.order.address
                  - else
                    = waybill.receiver.address
                td
                  = show_waybill_status waybill.status
                td
                  = date_time waybill.exp_time
                td
                  = date_time waybill.actual_time
                td = link_to 'Show', waybill

app/views/waybills/new.html.slim
h1 New waybill

== render 'form'

= link_to 'Back', waybills_path

app/views/waybills/show.html.slim
- if @waybill.receiver == current_courier
  .row
    .col-md-12
      .panel.panel-default
        .panel-heading#operations
          | 基本信息
        .panel-body
          table.table.table-striped
            tr
              td width='13%' 联系人
              td width='20%' = @waybill.order.user.name
              td width='13%' 联系方式
              td width='20%' = @waybill.order.user.mobile
              td width='13%' 取件地址
              td width='20%' = @waybill.order.address
            tr
              td width='13%' 当前状态
              td width='20%' = show_waybill_status @waybill.status
              td width='13%' 期望执行
              td width='20%' = date_time @waybill.exp_time
              td width='13%' 实际执行
              td width='20%' = date_time @waybill.actual_time

  = link_to '已取', yiqu_waybill_path(@waybill), method: :put, class: 'btn btn-info btn-sm' if @waybill.can_qujian?
  
  = link_to 'Back', waybills_path

.row
    .col-md-12
      .panel.panel-default
        .panel-heading#operations
          | 分拣信息
        .panel-body
          table.table.table-striped
            tr
              th 产品
              th 数量
              th 单价
              th 总价
              th
              th
            - @waybill.order.items.each do |item|
              tr
                td = item.product
                td = item.amount
                td = item.price
                td = item.amount * item.price
                td = link_to 'Edit', edit_waybill_item_path(@waybill, item)
                td = link_to 'Destroy', waybill_item_path(@waybill, item), data: { confirm: 'Are you sure?' }, method: :delete
        .panel-footer
          = link_to '分拣', new_waybill_item_path(@waybill), class: 'btn btn-info btn-sm'